# Generated by Django 4.2.5 on 2023-09-12 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_tareas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='updated',
            new_name='last_updated',
        ),
    ]
