# Generated by Django 4.2.5 on 2023-09-22 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_tareas', '0006_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='important',
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('ALTA', 'ALTA'), ('MEDIA', 'MEDIA'), ('BAJA', 'BAJA')], default='MEDIA', max_length=15),
        ),
    ]
